### ISSUE TITLE
How to use RunWithExternalLoop

### ISSUE THREAD

**Issue by James-Pickett** [fyne-io/systray#25]
Hello,

I'm trying to understand how [RunWithExternalLoop](https://github.com/fyne-io/systray/blob/master/systray.go#L80) works. Calling [Run](https://github.com/fyne-io/systray/blob/master/systray.go#L71) works as expected, but I was trying to see if I can not block the main thread using [RunWithExternalLoop](https://github.com/fyne-io/systray/blob/master/systray.go#L80), but nothing seems to happen. What am I missing here?

Running on:
macOS Montery 12.5
Apple M1 Pro

```go
package main

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"time"

	"fyne.io/systray"
)

func main() {
	onReady := func() {
		systray.SetIcon(blackBox())
		systray.SetTooltip("test")
	}

	// this works and blocks the main thread
	// systray.Run(onReady, func() {})

	// this does not not show anything in sys tray
	start, _ := systray.RunWithExternalLoop(onReady, func() {})
	start()

	// expect to see a black box in systray while sleeping
	time.Sleep(time.Second * 10)
}

func blackBox() []byte {
	// create an image
	img := image.NewRGBA(image.Rect(0, 0, 32, 32))

	// set all pixels to black
	for y := 0; y < 32; y++ {
		for x := 0; x < 32; x++ {
			img.Set(x, y, color.Black)
		}
	}

	// return image bytes
	buf := new(bytes.Buffer)
	png.Encode(buf, img)
	return buf.Bytes()
}
```

Thank you for your help!

**Comment by andydotxyz** [comment]
Blocking the main thread is not a runloop - no events can run or be handled etc.
The `RunWithExternalLoop` is for toolkits that need to control the main thread - if you are not using one then it will have to be simulated somehow.
This is not trivial as a graphical app (as all systray apps are) must handle the OS event etc.

You can see how Fyne does it at https://github.com/fyne-io/fyne/blob/638ae24e4bebfc0b6dbaabf8db5807eeabfafc61/internal/driver/glfw/driver_desktop.go#L32 - notice how the start and stop variables are stored to be called when the GUI app is ready, and when it will exit.

**Comment by James-Pickett** [comment]
Thanks for the response @andydotxyz! So if I am understanding correctly, `RunWithExternalLoop` should only be used when I have something else running on the main thread that handle the UI loop?

**Comment by andydotxyz** [comment]
Yes, that is a good way of putting it. Something has to run the mainloop.

**Comment by gedw99** [comment]
@James-Pickett GIOUI might work. Am going to try.

**Comment by andydotxyz** [comment]
It is unavoidable that some GUI toolkit must own/block the main loop. Fyne, Gio, Qt are all the same in this regard - it is simply required by most operating systems that GUI apps function this way.

Previous versions of `systray` only provided `Run` which meant that it would block. `RunWithExternalLoop` allows you to integrate with another toolkit. The reason there is not an example of using this with Fyne is because we encapsulate it - the whole project is hidden behind `myApp.(desktop.App).SetSyetemTrayMenu()` - a much cleaner API than the complexity of managing a system tray menu directly :).
