### ISSUE TITLE
Is there a way to change the title in the taskbar corner overflow menu in Windows 11?

### ISSUE THREAD

**Issue by vlabo** [fyne-io/systray#27]
![image](https://user-images.githubusercontent.com/7770953/195600686-88f62d8f-0cde-42df-b233-59f6209cf6ea.png)

Here is how to get to the settings
Settings > Personalisation > Taskbar > Taskbar Corner Overlfow

**Comment by andydotxyz** [comment]
This should come from the app metadata. If so it will be added when you package it for release, but not when you run the application as a simple executable from a local build...
But I could be wrong - if you can find any MS documentation that helps we could look further.

**Comment by andydotxyz** [comment]
I assume you already use `systray.SetTitle`?

**Comment by vlabo** [comment]
I did try `systray.SetTitle` but I didn't saw any effect on windows. 
I will try to look for documentation when I find some time for it.

**Comment by andydotxyz** [comment]
I have confirmed that this is part of app packaging. A tool like "fyne package" will indeed set the appropriate metadata so the app shows title.
The same data is used in "Task Manager" if that is easier to manage?
