### ISSUE TITLE
SetIcon() failed to set IconPixmap prop on Debian/Xfce

### ISSUE THREAD

**Issue by cvilsmeier** [fyne-io/systray#48]
Hi,

I need to update my app's systray icon based on the state of my application. But SetIcon() for updating the systray icon does not seem to work, it prints the following error message:
    
    2023/05/10 23:32:47 systray error: failed to set IconPixmap prop: dbus.Store: type mismatch: slice: cannot convert a value of []systray.PX into []systray.PX

I've created a small project to reproduce the bug:
https://github.com/cvilsmeier/fyne-tray-test

**Comment by andydotxyz** [comment]
Thanks for the report, confirmed.

**Comment by comron-cvilsmeier** [comment]
I tried fix/48 and it works for me.

**Comment by lgirma** [comment]
I am still getting that error.

Is this released and available?

**Comment by andydotxyz** [comment]
It was fixed a year back as you can see in the PR above.
This project does not have any formal release process so just asking Go to update the dependency or using @latest will get you all the fixes.
