### ISSUE TITLE
When added to autostart on windows, after reboot, the menu does not work

### ISSUE THREAD

**Issue by rkakrik** [fyne-io/systray#5]
When added to autostart on windows (adding shortcut to startup folder), after reboot, the tray icon appears, but the menu does not work.

**Comment by andydotxyz** [comment]
This may relate to your application software, we don't retain any state or start in different modes in any way.
Does the same thing happen with the demo app in `example` folder?

**Comment by rkakrik** [comment]
I'm sorry, the problem turned out to be the antivirus, which silently blocked the application.
