### ISSUE TITLE
Applications have same `Id` under Linux

### ISSUE THREAD

**Issue by leukipp** [fyne-io/systray#50]
The status notifier plugin on Linux (XFCE) allows you to rearrange tray icons.

When running the example app, it looks like the `Id` property (`"1"`) is used in this list:
![id-1](https://github.com/fyne-io/systray/assets/53117365/59057627-ea3e-4a8c-b259-a5da23873223)

All fyne-io/systray applications use the same entry and therefore cannot be rearranged/hidden individually. This property is hardcoded here:
https://github.com/fyne-io/systray/blob/b6a2d6ca2a7be3f45d6299fa7e02311667402595/systray_unix.go#L272

Changing the code section above to, 
```go
"Id": {
	Value:    t.title,
	...
},
```
will use the application `Title` in the list:
![id-title](https://github.com/fyne-io/systray/assets/53117365/a4789d8f-1fdc-4283-9f92-b1982a1d96c4)

I'm not sure if this modification violates some specifications or if the property is related to the one used in:
https://github.com/fyne-io/systray/blob/b6a2d6ca2a7be3f45d6299fa7e02311667402595/systray_unix.go#L178

If not, I would suggest this as a bug fix.

**Comment by Jacalz** [comment]
That does sound like a bug. Feel free to open a pull request. Contributions are always appreciated

**Comment by leukipp** [comment]
Any news if #51 can be merged?

**Comment by Jacalz** [comment]
Sorry. For the delay. We've been quite busy. I don't currently have any system tray set up for testing but I'll see that it get reviewed
