### ISSUE TITLE
Successive calls to `item.SetTitle` causes panic

### ISSUE THREAD

**Issue by gabe565** [fyne-io/systray#79]
Hi!

I had a quick question about 03c78c0eeffdba02e75ddec29d7942770ca1e9b0. After updating, successive calls to `item.SetTitle` causes my application to panic [on this line](https://github.com/gabe565/nightscout-menu-bar/blob/7ad5d4e1db5d0d70f44817d2437c9e526188801d/internal/tray/systray.go#L131) since the channel has already been closed:
```
panic: close of closed channel

goroutine 29 [running]:
fyne.io/systray.(*MenuItem).update(0x140000a6440)
	fyne.io/systray@v1.10.1-0.20240608091126-03c78c0eeffd/systray.go:273 +0x6c
fyne.io/systray.(*MenuItem).SetTitle(...)
	fyne.io/systray@v1.10.1-0.20240608091126-03c78c0eeffd/systray.go:199
github.com/gabe565/nightscout-menu-bar/internal/tray.(*Tray).onReady(0x140000c2000)
	github.com/gabe565/nightscout-menu-bar/internal/tray/systray.go:131 +0x354
fyne.io/systray.Register.func2()
	fyne.io/systray@v1.10.1-0.20240608091126-03c78c0eeffd/systray.go:112 +0x38
created by fyne.io/systray.Register in goroutine 1
	fyne.io/systray@v1.10.1-0.20240608091126-03c78c0eeffd/systray.go:110 +0xb8
exit status 2
```

My application updates the title every minute or so. Is `item.SetTitle` not intended to be used this way?

Thank you!

**Comment by andydotxyz** [comment]
`SetTitle` should be callable any number of times. It looks like the channel being closed is in subtly wrong scope.

**Comment by andydotxyz** [comment]
Should be fixed now, sorry for that

**Comment by gabe565** [comment]
No problem. Thank you for the quick fix! Love all of the work you do
