### ISSUE TITLE
RPI OS - Volume control / Calendar

### ISSUE THREAD

**Issue by shuttingdown** [fyne-io/systray#83]
Hello everyone!

I just noticed on a freshly installed* RPI OS (22 October version, with recommended desktop applications), that whenever I click on the taskbar on the Volume control button or onto the Calendar the wf-panel-pi task use up to 20-25 percent of CPU, and doesn't change, only if I click on the buttons again (close the Volume control or the Calendar window). This doesn't happen with the Bluetooth or Network buttons. The system is up to date. Anyone noticed this? Thank you in advance.

*It's installed on a Samsung sdcard, on an RPI 4, 8 GB version

**Comment by andydotxyz** [comment]
I don't think this has anything to do with the Fyne project. Or our system tray modules.
